// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIfs04S3BeIDU2_iTEdWq34Wk2ajNqKQs',
    appId: '1:403335848740:web:5214b6913a61ac572109b1',
    messagingSenderId: '403335848740',
    projectId: 'shopping-6b102',
    authDomain: 'shopping-6b102.firebaseapp.com',
    storageBucket: 'shopping-6b102.firebasestorage.app',
    measurementId: 'G-483M70VVMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Rhg8Aqcc_yapVy66tJkHlGJyLA7cC1E',
    appId: '1:403335848740:android:11105003a8482c432109b1',
    messagingSenderId: '403335848740',
    projectId: 'shopping-6b102',
    storageBucket: 'shopping-6b102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlapyK-0P1-O7S6b2yjhB-Ybi5mZzulsI',
    appId: '1:403335848740:ios:81b881046e0ef0832109b1',
    messagingSenderId: '403335848740',
    projectId: 'shopping-6b102',
    storageBucket: 'shopping-6b102.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlapyK-0P1-O7S6b2yjhB-Ybi5mZzulsI',
    appId: '1:403335848740:ios:81b881046e0ef0832109b1',
    messagingSenderId: '403335848740',
    projectId: 'shopping-6b102',
    storageBucket: 'shopping-6b102.firebasestorage.app',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIfs04S3BeIDU2_iTEdWq34Wk2ajNqKQs',
    appId: '1:403335848740:web:3661c6770ec0c4392109b1',
    messagingSenderId: '403335848740',
    projectId: 'shopping-6b102',
    authDomain: 'shopping-6b102.firebaseapp.com',
    storageBucket: 'shopping-6b102.firebasestorage.app',
    measurementId: 'G-BXCR195GXY',
  );
}
